CREATE TABLE public.users(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	email CHARACTER VARYING(320) NOT NULL,
	password CHARACTER VARYING(25) NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY(id),
	CONSTRAINT uc_users_email UNIQUE(email)
);

CREATE TABLE public.employees(
	id INT NOT NULL,
	first_name CHARACTER VARYING(35) NOT NULL,
	last_name CHARACTER VARYING(35) NOT NULL,
	CONSTRAINT pk_employees PRIMARY KEY(id),
	CONSTRAINT fk_employees_users FOREIGN KEY(id) REFERENCES public.users(id)
);

CREATE TABLE public.candidates(
	id INT NOT NULL,
	first_name CHARACTER VARYING(35) NOT NULL,
	last_name CHARACTER VARYING(35) NOT NULL,
	identity_number CHARACTER VARYING(11) NOT NULL,
	birth_day date NOT NULL,
	CONSTRAINT pk_candidates PRIMARY KEY(id),
	CONSTRAINT fk_candidates_users FOREIGN KEY(id) REFERENCES public.users(id),
	CONSTRAINT uc_candidates_identity_number UNIQUE(identity_number)
);

CREATE TABLE public.employers(
	id INT NOT NULL,
	company_name CHARACTER VARYING(255) NOT NULL,
	web_address CHARACTER VARYING(50) NOT NULL,
	phone_number CHARACTER VARYING(12) NOT NULL,
	CONSTRAINT pk_employers PRIMARY KEY(id),
	CONSTRAINT fk_employers_users FOREIGN KEY(id) REFERENCES public.users(id)
);

CREATE TABLE public.verification_codes(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	code CHARACTER VARYING(38) NOT NULL,
	is_verified BOOLEAN NOT NULL,
	verified_date DATE,
	CONSTRAINT pk_verification_codes PRIMARY KEY(id),
	CONSTRAINT uc_verification_codes_code UNIQUE(code)
);

CREATE TABLE public.verification_code_candidates(
	id INT NOT NULL,
	candidate_id INT NOT NULL,
	CONSTRAINT pk_verification_code_candidates PRIMARY KEY(id),
	CONSTRAINT fk_verification_code_candidates_verification_codes 
	FOREIGN KEY(id) REFERENCES public.verification_codes(id),
	CONSTRAINT fk_verification_code_candidates_candidates
	FOREIGN KEY(candidate_id) REFERENCES public.candidates(id)
);

CREATE TABLE public.verification_code_employers(
	id INT NOT NULL,
	employer_id INT NOT NULL,
	CONSTRAINT pk_verification_code_employers PRIMARY KEY(id),
	CONSTRAINT fk_verification_code_employers_verification_codes 
	FOREIGN KEY(id) REFERENCES public.verification_codes(id),
	CONSTRAINT fk_verification_code_employers_employers
	FOREIGN KEY(employer_id) REFERENCES public.employers(id)
);

CREATE TABLE public.employee_confirms(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	employee_id INT NOT NULL,
	is_confirmed BOOLEAN NOT NULL,
	confirm_date DATE NOT NULL,
	CONSTRAINT pk_employee_confirms PRIMARY KEY(id),
	CONSTRAINT fk_employee_confirms_employee_id FOREIGN KEY(employee_id) REFERENCES public.employees(id)
);

CREATE TABLE public.employee_confirm_employers(
	id INT NOT NULL,
	employer_id INT NOT NULL,
	CONSTRAINT pk_employee_confirm_employers PRIMARY KEY(id),
	CONSTRAINT fk_employee_confirm_employers_employee_confirms 
	FOREIGN KEY(id) REFERENCES public.employee_confirms(id),
	CONSTRAINT fk_employee_confirm_employers_employers
	FOREIGN KEY(employer_id) REFERENCES public.employers(id)
);

CREATE TABLE public.job_titles(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	title CHARACTER VARYING(255) NOT NULL,
	min_salary numeric(6,2),
	max_salary numeric(6,2),
	CONSTRAINT pk_job_titles PRIMARY KEY(id),
	CONSTRAINT uc_job_titles_title UNIQUE(title)
);



CREATE TABLE public.cities(
id INT  GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
city_name CHARACTER VARYING(60) NOT NULL,
CONSTRAINT pk_cities PRIMARY KEY(id),
CONSTRAINT uc_cities UNIQUE(id)
);


CREATE TABLE public.job_advertisements(
id INT  GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
employer_id INT NOT NULL,
job_title_id INT NOT NULL,
description CHARACTER VARYING(1000) NOT NULL,
city_id INT NOT NULL,
position_number INT NOT NULL,
release_date date  NOT NULL,
application_deadline date NOT NULL,
is_active BOOLEAN NOT NULL,
CONSTRAINT pk_job_advertisements PRIMARY KEY(id),
CONSTRAINT fk_job_advertisements_employers
FOREIGN KEY (employer_id) REFERENCES public.employers (id),
CONSTRAINT fk_job_advertisements_job_titles
FOREIGN KEY (job_title_id) REFERENCES public.job_titles (id)
CONSTRAINT fk_job_advertisements_cities
FOREIGN KEY(city_id) REFERENCES public.cities(id) 
);




CREATE TABLE public.cover_letters(
candidate_id INT NOT NULL PRIMARY KEY,
content CHARACTER VARYING(350) NOT NULL,

CONSTRAINT fk_cover_letters_candidates
FOREIGN KEY (candidate_id) REFERENCES public.candidates (id)
);


CREATE TABLE public.images(
id INT  GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1) PRIMARY KEY,
image_url  CHARACTER VARYING(1000) NOT NULL,
user_id INT NOT NULL,

CONSTRAINT fk_images_candidates
FOREIGN KEY (user_id) REFERENCES public.users (id)
);

CREATE TABLE public.work_experiences(
id INT  GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1) PRIMARY KEY,
business_name CHARACTER VARYING(60) NOT NULL,
begin_date date  NOT NULL,
end_date date ,
candidate_id INT NOT NULL,
job_title_id INT NOT NULL,

CONSTRAINT fk_work_experiences_candidates
FOREIGN KEY (candidate_id) REFERENCES public.candidates (id),
CONSTRAINT fk_work_experiences_job_titles
FOREIGN KEY (job_title_id) REFERENCES public.job_titles (id)
);



CREATE TABLE public.links(
id INT  GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1) PRIMARY KEY,
url_adrress CHARACTER VARYING(70) NOT NULL,
candidate_id INT NOT NULL,

CONSTRAINT fk_links_resumes
FOREIGN KEY (candidate_id) REFERENCES public.candidates (id)

);

CREATE TABLE public.languages(
id INT  GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1) PRIMARY KEY,
name CHARACTER VARYING(60) NOT NULL
);

CREATE TABLE public.resume_languages(
id INT  GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1) PRIMARY KEY,
language_id INT NOT NULL,
level INT NOT NULL,
candidate_id INT NOT NULL,
CONSTRAINT fk_resume_languages_languages
FOREIGN KEY (language_id) REFERENCES public.languages (id),
CONSTRAINT fk_resume_languages_candidates
FOREIGN KEY (candidate_id) REFERENCES public.candidates (id)
);

CREATE TABLE public.it_technologies(
id INT  GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1) PRIMARY KEY,
name CHARACTER VARYING(50) NOT NULL
);

CREATE TABLE public.resumes_it_technologies(
id INT  GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1) PRIMARY KEY,
it_technology_id INT NOT NULL,
candidate_id INT NOT NULL,

CONSTRAINT fk_it_technologies_candidates
FOREIGN KEY (candidate_id) REFERENCES public.candidates (id),
CONSTRAINT fk_it_technologies_resumes_it_technologies
FOREIGN KEY (it_technology_id) REFERENCES public.it_technologies (id)

);


CREATE TABLE public.universities(
id INT  GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1) PRIMARY KEY,
name CHARACTER VARYING(50) NOT NULL
);

CREATE TABLE public.university_departments(
id INT  GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1) PRIMARY KEY,
name CHARACTER VARYING(50) NOT NULL
);

CREATE TABLE public.educations(
id INT  GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1) PRIMARY KEY,
university_id INT NOT NULL,
university_department_id INT NOT NULL,
candidate_id INT NOT NULL,
begin_date date  NOT NULL,
end_date date ,

CONSTRAINT fk_educations_university_departments
FOREIGN KEY (university_department_id) REFERENCES public.university_departments (id),

CONSTRAINT fk_educations_universities
FOREIGN KEY (university_id) REFERENCES public.universities (id),

CONSTRAINT fk_educations_candidates
FOREIGN KEY (candidate_id) REFERENCES public.candidates (id)
);

